{:namespaces
 ({:source-url nil,
   :wiki-url "snout.core-api.html",
   :name "snout.core",
   :author "Eduardo Julian",
   :doc nil}
  {:source-url nil,
   :wiki-url "snout.macros-api.html",
   :name "snout.macros",
   :author "Eduardo Julian",
   :doc nil}),
 :vars
 ({:name "*history*",
   :namespace "snout.core",
   :source-url nil,
   :dynamic true,
   :raw-source-url nil,
   :wiki-url "/snout.core-api.html#snout.core/*history*",
   :doc "The history object.",
   :var-type "var",
   :line 19,
   :file "src/snout/core.clj"}
  {:arglists ([]),
   :name "create-history",
   :namespace "snout.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/snout.core-api.html#snout.core/create-history",
   :doc "",
   :var-type "function",
   :line 17,
   :file "src/snout/core.clj"}
  {:arglists ([]),
   :name "get-token",
   :namespace "snout.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/snout.core-api.html#snout.core/get-token",
   :doc "",
   :var-type "function",
   :line 21,
   :file "src/snout/core.clj"}
  {:arglists ([tok]),
   :name "set-token!",
   :namespace "snout.core",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/snout.core-api.html#snout.core/set-token!",
   :doc "",
   :var-type "function",
   :line 22,
   :file "src/snout/core.clj"}
  {:arglists ([route args & body]),
   :name "defroute",
   :namespace "snout.macros",
   :source-url nil,
   :raw-source-url nil,
   :wiki-url "/snout.macros-api.html#snout.macros/defroute",
   :doc
   "Given a route (the same style as a Clout route), an args-vector and a body,\ndefines a function that will be called when the fragment identifier of the current URL changes and is matched by the route.\nThe route will be passed :route :params as well as parameters like those of a GET request.\ne.g. (defroute \"/my/route/:arg1\" [arg1 arg2 arg3]\n       (js/alert (pr-str arg1 arg2 arg3)))",
   :var-type "macro",
   :line 16,
   :file "src/snout/macros.clj"})}
